INSERT INTO CUSTOMER (NAME, AGE, ACTIVE) VALUES ('Willian', 22, TRUE);
INSERT INTO CUSTOMER (NAME, AGE, ACTIVE) VALUES ('Mariah', 40, TRUE);
INSERT INTO CUSTOMER (NAME, AGE, ACTIVE) VALUES ('Artur', 24, FALSE);
